# Generated by Django 5.0.6 on 2024-08-21 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_parent_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=250)),
                ('prod_price', models.FloatField()),
                ('prod_quantity', models.IntegerField()),
                ('prod_descr', models.TextField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.category')),
            ],
            options={
                'db_table': 'proddetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_img', models.ImageField(upload_to='products/')),
                ('prod_img_date', models.DateTimeField(auto_now_add=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.product')),
            ],
            options={
                'db_table': 'prodimg',
                'managed': True,
            },
        ),
    ]
