# Generated by Django 5.0.6 on 2024-09-04 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_parent_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('ord_stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_status', models.CharField(db_column='order_status', max_length=500)),
                ('ord_track_no', models.FloatField(db_column='order_tracking_no')),
            ],
            options={
                'db_table': 'order_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('paym_id', models.AutoField(primary_key=True, serialize=False)),
                ('paymethod', models.CharField(db_column='payment_method', max_length=500)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('paystat_id', models.AutoField(primary_key=True, serialize=False)),
                ('paystat', models.CharField(db_column='payment_status', max_length=250)),
            ],
            options={
                'db_table': 'payment_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('ship_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipmnt_method', models.CharField(db_column='shipment_method', max_length=500, null=True)),
                ('shipmnt_cost', models.FloatField(db_column='shipment_cost')),
            ],
            options={
                'db_table': 'shipping_method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShippingStatus',
            fields=[
                ('ship_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipmnt_status', models.CharField(db_column='shipment_status', max_length=500)),
            ],
            options={
                'db_table': 'shipping_status',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=250)),
                ('prod_price', models.FloatField()),
                ('prod_quantity', models.IntegerField()),
                ('prod_descr', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.category')),
            ],
            options={
                'db_table': 'proddetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_img', models.ImageField(upload_to='products/')),
                ('prod_img_date', models.DateTimeField(auto_now_add=True)),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.product')),
            ],
            options={
                'db_table': 'prodimg',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('order_placed_at', models.DateField(auto_now_add=True, db_column='order_created_at')),
                ('order_total_amount', models.FloatField(db_column='total_amount')),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('post_code', models.CharField(max_length=500)),
                ('deliv_add', models.TextField()),
                ('deliv_instructions', models.TextField(blank=True, null=True)),
                ('is_gift', models.BooleanField(default=False)),
                ('order_stat', models.ForeignKey(db_column='order_status', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.orderstatus')),
                ('paym_id', models.ForeignKey(db_column='payment_method_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.paymentmethod')),
                ('paystat', models.ForeignKey(db_column='payment_status_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.paymentstatus')),
                ('prod', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.product')),
                ('ship_method', models.ForeignKey(db_column='shipping_method_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.shippingmethod')),
                ('ship_status', models.ForeignKey(db_column='shipment_status_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.shippingstatus')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.userprofile')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
    ]
