# Generated by Django 5.0.6 on 2024-09-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_appinterviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_stat',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('on the way', 'On the way'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.RemoveField(
            model_name='order',
            name='paym_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paystat',
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_method',
            field=models.CharField(choices=[('standard', 'Standard'), ('next day delivery', 'Next day delivery'), ('same day delivery', ' Same day delivery')], default='standard', max_length=50),
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prod',
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit/ debit card', 'Credit/Debit card'), ('paypal', 'Paypal')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_stat',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total_amount',
            field=models.FloatField(blank=True, db_column='total_amount', null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.userprofile')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(db_column='cart_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.cart'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('cart_item_id', models.AutoField(db_column='cart_item_id', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_appinterviewer.cart')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='ai_appinterviewer.product')),
            ],
            options={
                'db_table': 'cart_items',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
        migrations.DeleteModel(
            name='ShippingStatus',
        ),
    ]
