# Generated by Django 5.0.6 on 2024-08-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_appinterviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_parent_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='default_username', max_length=250),
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=250)),
                ('prod_price', models.FloatField()),
                ('prod_quantity', models.IntegerField()),
                ('prod_descr', models.TextField()),
                ('prod_image', models.ImageField(upload_to='products/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_appinterviewer.category')),
            ],
            options={
                'db_table': 'proddetails',
                'managed': True,
            },
        ),
    ]
