# Generated by Django 5.0.6 on 2024-09-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_appinterviewer', '0002_alter_order_order_stat_remove_order_paym_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='is_deleted',
        ),
    ]
