# Generated by Django 5.0.6 on 2024-09-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_appinterviewer', '0003_remove_cartitems_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
