# Generated by Django 5.0.6 on 2024-09-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_appinterviewer', '0004_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliv_instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_method',
        ),
    ]
